name: Build MAUI Windows

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install MAUI workload
      run: dotnet workload install maui

    # NO RESTORE â€” evita restaurar Android/iOS/Mac
    # DIRECTAMENTE PUBLICAMOS WINDOWS

    - name: Publish Windows
      run: dotnet publish TextileSystem.csproj `
            -c Release `
            -f net10.0-windows10.0.19041.0 `
            -r win10-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:PublishDir=output `
            --no-restore
      shell: powershell

    - name: Zip Build
      run: |
        Compress-Archive -Path output\* -DestinationPath TextileSystem-Windows.zip
      shell: powershell

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TextileSystem-Windows
        path: TextileSystem-Windows.zip
