name: Build MAUI Windows

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x   # mejor usar LTS

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Restore
      run: dotnet restore TextileSystem.csproj

    - name: Publish Windows
      run: dotnet publish TextileSystem.csproj `
            -c Release `
            -f net8.0-windows10.0.19041.0 `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -o output
      shell: powershell

    - name: Zip Build Output
      run: Compress-Archive -Path "output\*" -DestinationPath TextileSystem-Windows.zip
      shell: powershell

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TextileSystem-Windows
        path: TextileSystem-Windows.zip
